/**
 * content.js — Point d'entrée de l'Agent Adapter Hack
 *
 * Chargé en world: MAIN (accès à navigator.modelContext, PAS aux chrome.* APIs).
 * Dépend de configs-bundle.js, dom-analyzer.js et injector.js chargés avant lui.
 *
 * Flux :
 *   1. Vérifier le support WebMCP (navigator.modelContext)
 *   2. Rechercher une config dans AGENT_ADAPTER_CONFIGS par hostname
 *   3. Si pas de config → tenter une analyse heuristique du DOM
 *   4. Attendre que le sélecteur waitFor soit présent dans le DOM
 *   5. Enregistrer les tools via navigator.modelContext.registerTool()
 *   6. Publier l'état dans window.__agentAdapterState pour le popup
 */

(async () => {
  const STATE_KEY = '__agentAdapterState';

  function setState(state) {
    window[STATE_KEY] = { ...window[STATE_KEY], ...state, updatedAt: Date.now() };
  }

  setState({ status: 'loading', hostname: window.location.hostname, tools: [] });

  // 1. Support WebMCP
  const modelContext = document.modelContext || navigator.modelContext || null;
  if (!modelContext) {
    setState({ status: 'no-webmcp' });
    console.warn('[AgentAdapter] modelContext non disponible (document ni navigator).');
    console.warn('[AgentAdapter] Activer le flag : chrome://flags/#webmcp-for-testing');
    return;
  }

  // Chrome sérialise inputSchema en chaîne JSON dans getTools() — le panel WebMCP
  // attend un objet. On patch getTools() pour désérialiser à la volée.
  const _origGetTools = modelContext.getTools.bind(modelContext);
  modelContext.getTools = async () => {
    console.log('COUCOU')
    const tools = await _origGetTools();
    console.log({tools})
    return (tools ?? []).map(t => {
      if (typeof t.inputSchema !== 'string') return t;
      try {
        return { ...t, inputSchema: JSON.parse(t.inputSchema) };
      } catch {
        return t;
      }
    });
  };

  const hostname = window.location.hostname;
  const configKey = hostname.replace(/\./g, '-');
  console.log(`[AgentAdapter] Site détecté : ${hostname}`);

  // 2. Chercher la config dans le bundle
  let config = (typeof AGENT_ADAPTER_CONFIGS !== 'undefined')
    ? AGENT_ADAPTER_CONFIGS[configKey] ?? null
    : null;

  let isAutoGenerated = false;

  // 3. Fallback : analyse heuristique du DOM
  if (!config) {
    console.log(`[AgentAdapter] Aucune config pour "${hostname}", analyse heuristique du DOM…`);
    const autoTools = analyzeDOMForTools();

    if (autoTools.length > 0) {
      console.log(`[AgentAdapter] ${autoTools.length} tool(s) détecté(s) automatiquement.`);
      config = {
        name: `Auto-adapter (${hostname})`,
        hostname,
        waitFor: null,
        tools: autoTools
      };
      isAutoGenerated = true;
    } else {
      setState({ status: 'no-config' });
      console.log(`[AgentAdapter] Aucun tool détecté automatiquement pour ${hostname}.`);
      return;
    }
  }

  // 4. Attendre le sélecteur waitFor
  if (config.waitFor) {
    await waitForElement(config.waitFor);
  }

  // 4b. Accepter les modals de cookies/consent au chargement
  if (config.dismissOnLoad?.length) {
    for (const dismiss of config.dismissOnLoad) {
      try {
        let target = null;
        if (dismiss.waitForSelector) await waitForElement(dismiss.waitForSelector);
        const candidates = document.querySelectorAll(dismiss.selector);
        if (dismiss.textMatch) {
          target = Array.from(candidates).find(el => el.textContent.includes(dismiss.textMatch)) ?? null;
        } else {
          target = candidates[0] ?? null;
        }
        if (target) {
          target.click();
          if (dismiss.waitMs) await new Promise(r => setTimeout(r, dismiss.waitMs));
          console.log(`[AgentAdapter] ✅ Modal dismissed : "${dismiss.textMatch ?? dismiss.selector}"`);
        }
      } catch (e) {
        // Modal absente ou déjà fermée — ignorer silencieusement
      }
    }
  }

  // 5. Enregistrer les tools
  const registered = [];
  const failed = [];
  const executors = {};

  for (const toolDef of config.tools) {
    try {
      const executor = buildExecutor(toolDef.action);
      executors[toolDef.name] = executor;
      modelContext.registerTool({
        name: toolDef.name,
        description: toolDef.description,
        inputSchema: toolDef.inputSchema,
        execute: executor
      });
      registered.push({ name: toolDef.name, description: toolDef.description });
      console.log(`[AgentAdapter] ✅ Tool enregistré : ${toolDef.name}`);
    } catch (err) {
      failed.push(toolDef.name);
      console.error(`[AgentAdapter] ❌ Erreur pour ${toolDef.name} :`, err);
    }
  }

  // Exposer un point d'entrée direct pour les scripts d'agent (evaluate_script).
  // executeTool() de l'API WebMCP ne fonctionne pas depuis les scripts de page dans
  // l'implémentation Chrome preview — __agentAdapterExecute contourne cette limitation.
  window.__agentAdapterExecute = async function(toolName, args) {
    const executor = executors[toolName];
    if (!executor) throw new Error(`[AgentAdapter] Tool inconnu : ${toolName}`);
    return await executor(args);
  };

  // 6. Reprendre une action différée (navigate_then_fill)
  const pendingRaw = sessionStorage.getItem('__agentAdapterPending');
  if (pendingRaw) {
    sessionStorage.removeItem('__agentAdapterPending');
    try {
      const { toolName, waitForSelector, args } = JSON.parse(pendingRaw);
      const executor = executors[toolName];
      if (executor) {
        if (waitForSelector) await waitForElement(waitForSelector);
        console.log(`[AgentAdapter] Reprise de l'action différée : ${toolName}`);
        await executor(args);
      } else {
        console.warn(`[AgentAdapter] Action différée ignorée : tool "${toolName}" inconnu`);
      }
    } catch (err) {
      console.error('[AgentAdapter] Erreur lors de l\'exécution différée :', err);
    }
  }

  // 6b. Reprendre un multi_step interrompu par une navigation cross-page
  const resumeRaw = sessionStorage.getItem('__agentAdapterResume');
  if (resumeRaw) {
    sessionStorage.removeItem('__agentAdapterResume');
    try {
      const { steps, args, waitFor: crossPageWaitFor } = JSON.parse(resumeRaw);
      console.log(`[AgentAdapter] Reprise cross-page : ${steps.length} step(s) restants`);
      if (crossPageWaitFor) await waitForElement(crossPageWaitFor);
      const resumeExecutor = buildExecutor({ type: 'multi_step', steps });
      await resumeExecutor(args);
    } catch (err) {
      console.error('[AgentAdapter] Erreur lors de la reprise cross-page :', err);
    }
  }

  // 6c. Reprendre un multi_step interrompu par une navigation SPA (hashchange)
  window.addEventListener('hashchange', async () => {
    const raw = sessionStorage.getItem('__agentAdapterResume');
    if (!raw) return;
    sessionStorage.removeItem('__agentAdapterResume');
    try {
      const { steps, args, waitFor: waitForSel } = JSON.parse(raw);
      console.log(`[AgentAdapter] Reprise hashchange : ${steps.length} step(s) restants`);
      if (waitForSel) await waitForElement(waitForSel);
      const resumeExecutor = buildExecutor({ type: 'multi_step', steps });
      await resumeExecutor(args);
    } catch (err) {
      console.error('[AgentAdapter] Erreur lors de la reprise hashchange :', err);
    }
  });

  // 7. Publier l'état pour le popup
  setState({
    status: 'active',
    configName: config.name,
    isAutoGenerated,
    tools: registered,
    failedTools: failed
  });

  const summary = isAutoGenerated ? '(auto-détecté)' : `(config: ${config.name})`;
  console.log(
    `[AgentAdapter] ✅ ${registered.length} tool(s) WebMCP injectés sur ${hostname} ${summary}`
  );
})();

// ---------------------------------------------------------------------------

function waitForElement(selector) {
  return new Promise(resolve => {
    if (document.querySelector(selector)) {
      resolve();
      return;
    }
    const observer = new MutationObserver(() => {
      if (document.querySelector(selector)) {
        observer.disconnect();
        resolve();
      }
    });
    observer.observe(document.documentElement, { childList: true, subtree: true });
    setTimeout(() => { observer.disconnect(); resolve(); }, 8000); // timeout de sécurité
  });
}
