/**
 * popup.js — Interface utilisateur de l'extension
 *
 * S'exécute dans le contexte de l'extension (accès complet aux chrome.* APIs).
 * Lit l'état depuis window.__agentAdapterState dans le monde MAIN de l'onglet
 * actif via chrome.scripting.executeScript({ world: 'MAIN' }).
 */

document.addEventListener('DOMContentLoaded', async () => {
  await renderPopup();
});

async function renderPopup() {
  const app = document.getElementById('app');

  try {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });

    if (!tab?.id || isRestrictedUrl(tab.url)) {
      app.innerHTML = buildStateMessage(
        'Page non accessible',
        "L'extension ne peut pas s'injecter sur les pages système Chrome ou les nouvelles pages.",
        ''
      );
      return;
    }

    // Lire l'état depuis le monde MAIN de l'onglet actif
    let state = null;
    try {
      const results = await chrome.scripting.executeScript({
        target: { tabId: tab.id },
        world: 'MAIN',
        func: () => window.__agentAdapterState ?? null
      });
      state = results?.[0]?.result ?? null;
    } catch {
      // Le script n'a pas encore tourné (page en cours de chargement, etc.)
      state = null;
    }

    const hostname = new URL(tab.url).hostname;
    app.innerHTML = buildFullUI(state, hostname);

    // Bouton rafraîchir
    document.getElementById('btn-refresh')?.addEventListener('click', async () => {
      app.innerHTML = '<div class="loading"><div class="spinner"></div><span>Rafraîchissement…</span></div>';
      await new Promise(r => setTimeout(r, 300));
      await renderPopup();
    });

    // Bouton agent : ouvre le side panel (chat) pour l'onglet courant.
    // Le clic du popup fournit le geste utilisateur requis par chrome.sidePanel.open().
    document.getElementById('btn-agent')?.addEventListener('click', async () => {
      try {
        await chrome.sidePanel.open({ tabId: tab.id });
        window.close();
      } catch (err) {
        console.error('[AgentAdapter] Ouverture du side panel impossible :', err);
      }
    });

  } catch (err) {
    app.innerHTML = buildStateMessage(
      'Erreur',
      `Impossible de lire l'état de la page : ${err.message}`,
      ''
    );
  }
}

// ---------------------------------------------------------------------------

function buildFullUI(state, hostname) {
  const webmcpStatus = getWebMCPStatus(state);
  const configStatus = getConfigStatus(state);
  const tools = state?.tools ?? [];
  const isAuto = state?.isAutoGenerated ?? false;

  return `
    <div class="status-section">
      <div class="status-row">
        <span class="status-label">WebMCP</span>
        ${webmcpStatus.badge}
      </div>
      <div class="status-row">
        <span class="status-label">Config</span>
        ${configStatus.badge}
      </div>
    </div>

    ${tools.length > 0 ? buildToolsList(tools, isAuto) : buildNoTools(state)}

    <div class="footer">
      <span class="footer-site" style="font-size:11px;color:#4040a0">${hostname}</span>
      <div style="display:flex;gap:6px">
        <button class="btn-refresh" id="btn-agent">🤖 Agent</button>
        <button class="btn-refresh" id="btn-refresh">↺ Rafraîchir</button>
      </div>
    </div>
  `;
}

function buildToolsList(tools, isAuto) {
  const cards = tools.map(tool => `
    <div class="tool-card">
      <div class="tool-name">
        ${escapeHtml(tool.name)}
        ${isAuto ? '<span class="tool-auto-badge">auto</span>' : ''}
      </div>
      <div class="tool-desc">${escapeHtml(tool.description)}</div>
    </div>
  `).join('');

  return `
    <div class="tools-section">
      <div class="tools-header">
        <span class="tools-title">Tools actifs</span>
        <span class="tools-count">${tools.length}</span>
      </div>
      <div class="tools-list">${cards}</div>
    </div>
  `;
}

function buildNoTools(state) {
  if (!state || state.status === 'loading') {
    return buildStateMessage(
      'En attente…',
      'Le script n\'a pas encore fini de s\'exécuter. Rechargez la page ou attendez.',
      ''
    );
  }
  if (state.status === 'no-webmcp') {
    return buildStateMessage(
      'WebMCP non disponible',
      'Activez le flag dans Chrome :',
      '<code>chrome://flags/#webmcp-for-testing</code>'
    );
  }
  if (state.status === 'no-config') {
    return buildStateMessage(
      'Aucune config pour ce site',
      'Ajoutez une entrée dans configs-bundle.js ou le DOM analyzer n\'a pas trouvé de formulaires.',
      ''
    );
  }
  return buildStateMessage('Aucun tool actif', 'Aucun tool WebMCP n\'a été enregistré.', '');
}

function buildStateMessage(title, message, extra) {
  return `
    <div class="state-message">
      <strong>${escapeHtml(title)}</strong>
      ${escapeHtml(message)}
      ${extra}
    </div>
  `;
}

// ---------------------------------------------------------------------------

function getWebMCPStatus(state) {
  if (!state || state.status === 'loading') {
    return { badge: badge('gray', '⏳ En attente') };
  }
  if (state.status === 'no-webmcp') {
    return { badge: badge('red', '✗ Non disponible') };
  }
  return { badge: badge('green', '✓ Activé') };
}

function getConfigStatus(state) {
  if (!state || state.status === 'loading') {
    return { badge: badge('gray', '—') };
  }
  if (state.status === 'no-webmcp') {
    return { badge: badge('gray', '—') };
  }
  if (state.status === 'no-config') {
    return { badge: badge('red', '✗ Aucune config') };
  }
  if (state.isAutoGenerated) {
    return { badge: badge('yellow', '⚡ Auto-détecté') };
  }
  return { badge: badge('blue', `📋 ${escapeHtml(state.configName ?? 'Config OK')}`) };
}

function badge(color, text) {
  return `<span class="badge badge-${color}"><span class="dot"></span>${text}</span>`;
}

function isRestrictedUrl(url) {
  if (!url) return true;
  return url.startsWith('chrome://') ||
    url.startsWith('chrome-extension://') ||
    url.startsWith('about:') ||
    url.startsWith('edge://');
}

function escapeHtml(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
